name: Setup Build environment
description: Set up Scala, load cache

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: "corretto"
        java-version: "23"
        cache: "sbt"
    - name: Setup SBT
      uses: sbt/setup-sbt@v1
      with:
        sbt-runner-version: 1.10.7